import { useState, useEffect, useImperativeHandle, forwardRef } from "react";
import "./GraphPlayToolbar.css";
import { FaPlay } from "react-icons/fa";
import { generateUniformGridGraph } from "../algorithms/graphGenerator";
import { ColoringAlgorithmManager } from "../algorithms";

const manager = new ColoringAlgorithmManager();

const COLOR_MAP = {
  blue: "#3498db",
  green: "#2ecc71",
  yellow: "#f1c40f",
  purple: "#9b59b6",
  orange: "#e67e22",
  cyan: "#1abc9c",
  pink: "#ff6bcb",
  gray: "#bdc3c7",
};

const AVAILABLE_COLORS = [
  { value: "blue", label: "🔵 Azul" },
  { value: "green", label: "🟢 Verde" },
  { value: "yellow", label: "🟡 Amarillo" },
  { value: "purple", label: "🟣 Morado" },
  { value: "orange", label: "🟠 Naranja" },
  { value: "cyan", label: "🟦 Cian" },
  { value: "pink", label: "🌸 Rosa" },
  { value: "gray", label: "⚪ Gris" },
];

// =====  Completar grafo  =====
const completeGraphToMinimumNodes = (nodes, edges, minimumNodes = 60) => {
  if (nodes.length >= minimumNodes) {
    return { nodes: [...nodes], edges: [...edges] };
  }
  
  console.log(`🔄 Modo Manual: Solo hay ${nodes.length} nodos. Completando a ${minimumNodes}...`);
  
  const newNodes = [...nodes];
  const newEdges = [...edges];
  
  const existingPositions = new Set();
  nodes.forEach(n => {
    const roundedX = Math.round(n.position.x / 20) * 20;
    const roundedY = Math.round(n.position.y / 20) * 20;
    existingPositions.add(`${roundedX},${roundedY}`);
  });
  
  const existingNodeIds = nodes.map(n => n.id);
  const nodesToAdd = minimumNodes - nodes.length;
  
  for (let i = 0; i < nodesToAdd; i++) {
    let attempts = 0;
    let newX, newY;
    
    do {
      newX = 50 + Math.random() * 700;
      newY = 50 + Math.random() * 500;
      attempts++;
      
      if (attempts > 50) break;
    } while (
      Array.from(existingPositions).some(pos => {
        const [x, y] = pos.split(',').map(Number);
        const distance = Math.sqrt(Math.pow(x - newX, 2) + Math.pow(y - newY, 2));
        return distance < 50;
      })
    );
    
    const newNodeId = `auto_node_${Date.now()}_${i}`;
    newNodes.push({
      id: newNodeId,
      type: "circle",
      position: { x: newX, y: newY },
      data: { 
        label: `N${nodes.length + i + 1}`,
        isAutoGenerated: true
      }
    });
    
    const roundedX = Math.round(newX / 20) * 20;
    const roundedY = Math.round(newY / 20) * 20;
    existingPositions.add(`${roundedX},${roundedY}`);
    
    if (existingNodeIds.length > 0) {
      const connections = Math.min(3, Math.floor(Math.random() * 3) + 1);
      const connectedNodes = new Set();
      
      for (let j = 0; j < connections; j++) {
        let targetNode;
        let attemptsConnection = 0;
        
        do {
          targetNode = existingNodeIds[Math.floor(Math.random() * existingNodeIds.length)];
          attemptsConnection++;
          if (attemptsConnection > 10) break;
        } while (connectedNodes.has(targetNode));
        
        if (targetNode) {
          newEdges.push({
            id: `auto_edge_${Date.now()}_${i}_${j}`,
            source: newNodeId,
            target: targetNode,
            style: { stroke: '#ffffff', strokeWidth: 1.5 }
          });
          connectedNodes.add(targetNode);
        }
      }
    }
    
    existingNodeIds.push(newNodeId);
  }
  
  const newNodesAdded = newNodes.slice(nodes.length).map(n => n.id);
  if (newNodesAdded.length >= 3) {
    for (let i = 0; i < newNodesAdded.length - 1; i += 3) {
      if (i + 1 < newNodesAdded.length) {
        newEdges.push({
          id: `auto_edge_group_${Date.now()}_${i}`,
          source: newNodesAdded[i],
          target: newNodesAdded[i + 1],
          style: { stroke: '#ffffff', strokeWidth: 1.5 }
        });
      }
      if (i + 2 < newNodesAdded.length) {
        newEdges.push({
          id: `auto_edge_group_${Date.now()}_${i}_1`,
          source: newNodesAdded[i + 1],
          target: newNodesAdded[i + 2],
          style: { stroke: '#ffffff', strokeWidth: 1.5 }
        });
      }
    }
  }
  
  console.log(`✅ Se agregaron ${nodesToAdd} nodos automáticamente. Total: ${newNodes.length} nodos`);
  return { nodes: newNodes, edges: newEdges };
};


export default forwardRef(function GraphPlayToolbar({ graphCanvasRef, onAttemptsUpdate, onSelectedAttemptChange, onReset }, ref) {
  const [colorCount, setColorCount] = useState(3);
  const [selectedColors, setSelectedColors] = useState([
    "blue",
    "purple",
    "yellow",
  ]);
  const [limitHit, setLimitHit] = useState(false);
  const [isExecuting, setIsExecuting] = useState(false);

  const [attempts, setAttempts] = useState([]);
  const [currentAttemptIndex, setCurrentAttemptIndex] = useState(null);
  const [selectedAlgorithm, setSelectedAlgorithm] = useState("las_vegas");
  const [findValidSolution, setFindValidSolution] = useState("yes");
  const [acceptanceProbability, setAcceptanceProbability] = useState(0.5);
  const [numberOfAttempts, setNumberOfAttempts] = useState(50);

  const clearAttempts = () => {
    console.log("Clearing attempts in GraphPlayToolbar");
    setAttempts([]);
    setCurrentAttemptIndex(null);
  };

  useImperativeHandle(ref, () => ({
    clearAttempts,
  }), []);

  useEffect(() => {
    if (selectedColors.length > colorCount) {
      setSelectedColors((prev) => prev.slice(0, colorCount));
    }
  }, [colorCount, selectedColors.length]);

  useEffect(() => {
    if (limitHit) {
      const t = setTimeout(() => setLimitHit(false), 600);
      return () => clearTimeout(t);
    }
  }, [limitHit]);

  const handleColorCountChange = (e) => {
    const value = Number(e.target.value);
    if (value >= 3 && value <= 10) {
      setColorCount(value);
    }
  };

  const toggleColor = (value) => {
    if (selectedColors.includes(value)) {
      setSelectedColors((prev) => prev.filter((c) => c !== value));
      return;
    }

    if (selectedColors.length < colorCount) {
      setSelectedColors((prev) => [...prev, value]);
      return;
    }

    setLimitHit(true);
  };

  const handlePlayClick = () => {
    if (!graphCanvasRef?.current) return;

    setIsExecuting(true);

    setTimeout(() => {
      const currentAlgorithm = selectedAlgorithm;
      const algorithmName = currentAlgorithm === "las_vegas" ? "Las Vegas" : "Monte Carlo";

      let { nodes, edges } =
        typeof graphCanvasRef.current.getGraph === "function"
          ? graphCanvasRef.current.getGraph()
          : { nodes: [], edges: [] };

      // ===== Completar a 60 nodos si esta en modo manual =====
      const isManualMode = window.location.pathname.includes("/manual");
      if (isManualMode && nodes.length < 60) {
        console.log(`📊 Modo Manual detectado. Nodos actuales: ${nodes.length}. Necesarios: 60`);
        const completedGraph = completeGraphToMinimumNodes(nodes, edges, 60);
        nodes = completedGraph.nodes;
        edges = completedGraph.edges;
        
        graphCanvasRef.current.setGraph(nodes, edges);
        console.log(`✅ Grafo completado a ${nodes.length} nodos`);
      }

      if (!nodes || nodes.length === 0) {
        const nodeCount = Math.floor(Math.random() * (150 - 100 + 1)) + 100;
        const gridGraph = generateUniformGridGraph(nodeCount);
        nodes = gridGraph.nodes;
        edges = gridGraph.edges;
      }

      const adjacency = new Map(
        nodes.map((n, idx) => [String(n.id ?? idx + 1), new Set()])
      );

      edges.forEach((e) => {
        const a = String(e.source);
        const b = String(e.target);
        if (adjacency.has(a) && adjacency.has(b)) {
          adjacency.get(a).add(b);
          adjacency.get(b).add(a);
        }
      });

      const baseGraphForAlgo = nodes.map((n, idx) => {
        const id = String(n.id ?? idx + 1);
        return [id, 0, Array.from(adjacency.get(id) ?? [])];
      });

      const baseNodes = nodes.map((n, idx) => ({
        ...n,
        id: String(n.id ?? idx + 1),
      }));

      const k = selectedColors.length;
      if (k < 3) {
        alert("Se necesitan al menos 3 colores.");
        setIsExecuting(false);
        return;
      }

      const newBatch = [];
      let lastGraph = baseNodes;
      const batchStartTime = performance.now();
      const allIterations = [];
      const allConflicts = [];

      // ===== EJECUTAR N INTENTOS =====
      for (let i = 0; i < numberOfAttempts; i++) {

        const result = manager.executeAlgorithm(
          currentAlgorithm,
          baseGraphForAlgo,
          k,
          { 
            maxIterations: 2000,
            findValidSolution: findValidSolution === "yes",
            acceptanceProbability: parseFloat(acceptanceProbability)
          }
        );

        const colorMapAlgo = new Map(
          (result.coloring || []).map(([id, idxColor]) => [
            String(id),
            idxColor,
          ])
        );

        const coloredNodes = baseNodes.map((n) => {
          const id = String(n.id);
          const colorIndex = colorMapAlgo.get(id) ?? 0;
          const paletteIndex = colorIndex % k;
          const colorName = selectedColors[paletteIndex];
          const displayColor = COLOR_MAP[colorName] || colorName || "#e74c3c";

          return {
            ...n,
            data: {
              ...(n.data || {}),
              colorIndex,
              displayColor,
            },
          };
        });

        const stats = result.stats || {};
        const iterationData = {
          iteration: i + 1,
          totalIterations: stats.iterations || 0,
          totalConflicts: stats.conflicts || 0,
          executionTime: stats.execution_time || 0,
          isSuccessful: stats.success !== false,
        };

        allIterations.push(stats.iterations || 0);
        allConflicts.push(stats.conflicts || 0);

        newBatch.push({
          id: attempts.length + newBatch.length + 1,
          timestamp: new Date().toLocaleTimeString(),
          nodes: JSON.parse(JSON.stringify(coloredNodes)),
          edges: JSON.parse(JSON.stringify(edges)),
          palette: [...selectedColors],
          k,
          algorithm: algorithmName,
          ...iterationData,
          conflictsByIteration: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map(() => 
            Math.max(0, stats.conflicts - Math.random() * 2)
          ), 
        });

        lastGraph = coloredNodes;
      }

      const batchEndTime = performance.now();
      const avgExecutionTime = (batchEndTime - batchStartTime) / 50;

      const updatedAttempts = [...attempts, ...newBatch];
      setAttempts(updatedAttempts);
      
      if (onAttemptsUpdate) {
        onAttemptsUpdate(updatedAttempts);
      }

      const newIndex = updatedAttempts.length - 1;
      setCurrentAttemptIndex(newIndex);
      
      if (onSelectedAttemptChange) {
        onSelectedAttemptChange(newIndex);
      }

      graphCanvasRef.current.setGraph(lastGraph, edges);
      setIsExecuting(false);
    }, 100);
  };

  const handleLoadAttempt = (index) => {
    const att = attempts[index];
    if (!att || !graphCanvasRef?.current) return;
    setCurrentAttemptIndex(index);
    
    if (onSelectedAttemptChange) {
      onSelectedAttemptChange(index);
    }
    
    graphCanvasRef.current.setGraph(att.nodes, att.edges);
  };

  const canPlay = selectedColors.length === colorCount;

  return (
    <div className="graph-play-toolbar">
      {/* Overlay de carga */}
      {isExecuting && (
        <div className="loading-overlay">
          <div className="loading-spinner"></div>
          <p className="loading-text">Ejecutando algoritmo...</p>
        </div>
      )}

      <h3>Ejecución</h3>

      <button
        className="play-button"
        disabled={!canPlay || isExecuting}
        aria-disabled={!canPlay || isExecuting}
        title={
          canPlay
            ? "Ejecutar algoritmo"
            : `Selecciona ${colorCount} colores`
        }
        onClick={handlePlayClick}
      >
        <FaPlay className="play-icon" />
        <span className="play-text">Ejecutar algoritmo</span>
      </button>

      <label>Elegir algoritmo de ejecución:</label>
      <select 
        className="select-algorithm"
        value={selectedAlgorithm}
        onChange={(e) => setSelectedAlgorithm(e.target.value)}
        disabled={isExecuting}
      >
        <option value="las_vegas">Las vegas</option>
        <option value="monte_carlo">Monte Carlo</option>
      </select>

      <div className="option-select">
        <label>Encontrar solución válida:</label>
        <select 
          className="select-valid-solution"
          value={findValidSolution}
          onChange={(e) => setFindValidSolution(e.target.value)}
          disabled={isExecuting}
        >
          <option value="yes">Sí</option>
          <option value="no">No</option>
        </select>
      </div>

      {selectedAlgorithm === "monte_carlo" && (
        <div className="option-select">
          <label>Probabilidad de aceptación:</label>
          <input
            type="range"
            min="0.1"
            max="1"
            step="0.1"
            value={acceptanceProbability}
            onChange={(e) => setAcceptanceProbability(parseFloat(e.target.value))}
            className="probability-slider"
            disabled={isExecuting}
          />
          <span className="probability-value">{acceptanceProbability.toFixed(1)}</span>
        </div>
      )}

      <div className="option-select">
        <label>Cantidad de intentos:</label>
        <select 
          className="select-attempts"
          value={numberOfAttempts}
          onChange={(e) => setNumberOfAttempts(parseInt(e.target.value))}
          disabled={isExecuting}
        >
          <option value="10">10</option>
          <option value="25">25</option>
          <option value="50">50</option>
          <option value="100">100</option>
          <option value="200">200</option>
        </select>
      </div>

      <div className="color-config">
        <label>Cantidad de colores</label>
        <input
          type="number"
          min={3}
          max={10}
          value={colorCount}
          onChange={handleColorCountChange}
          disabled={isExecuting}
        />
      </div>

      <div className={`color-grid ${limitHit ? "limit-hit" : ""}`}>
        <label>Colores disponibles</label>
        <div
          className="color-options"
          role="listbox"
          aria-multiselectable="true"
        >
          {AVAILABLE_COLORS.map((c) => {
            const selected = selectedColors.includes(c.value);
            return (
              <button
                key={c.value}
                type="button"
                role="option"
                aria-pressed={selected}
                className={`color-option ${c.value} ${
                  selected ? "selected" : ""
                }`}
                onClick={() => toggleColor(c.value)}
                disabled={isExecuting}
              >
                <span className="color-emoji">
                  {c.label.split(" ")[0]}
                </span>
                <span className="color-name">
                  {c.label.split(" ").slice(1).join(" ")}
                </span>
                {selected && <span className="checkmark">✓</span>}
              </button>
            );
          })}
        </div>
        <div className="color-counter">
          {selectedColors.length} / {colorCount}
        </div>
      </div>

      {/* Lista de intentos */}
      <div className="attempts-panel">
        <h4>Intentos guardados</h4>
        {attempts.length === 0 && (
          <p className="attempts-empty">Todavía no hay intentos</p>
        )}
        <div className="attempts-list">
          {attempts.map((att, idx) => (
            <button
              key={att.id}
              className={
                idx === currentAttemptIndex
                  ? "attempt-button active"
                  : "attempt-button"
              }
              onClick={() => handleLoadAttempt(idx)}
              disabled={isExecuting}
            >
              #{att.id} – {att.timestamp}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
});